### PR TITLE
STDTC-77 format numbers with NumberFormat component

### PR DESCRIPTION
**Pull request by zburke**
Use `react-intl`'s `<FormatNumber>` component to display numbers with thousands separators according to the current locale.

Refs [STDTC-77](https://issues.folio.org/browse/STDTC-77)

Attn: @uladislausamets please merge this if you're OK with it and Ann-Marie approves of the ticket; I don't have write privileges in this repository.

### CODE REVIEW

**Comment by zburke** [comment]
@uladislausamets : I fixed the test's render context so it passes now, but you'll need to [pull down my fork and push it back to origin](https://dev.folio.org/guidelines/github-actions-frontend/#forked-repositories) for the CI build to succeed with publishing test results. Alternatively, you can ask DevOps to grant me access to this repo and I can push it there myself.

**Comment by uladislausamets** [comment]
> @uladislausamets : I fixed the test's render context so it passes now, but you'll need to [pull down my fork and push it back to origin](https://dev.folio.org/guidelines/github-actions-frontend/#forked-repositories) for the CI build to succeed with publishing test results. Alternatively, you can ask DevOps to grant me access to this repo and I can push it there myself. 

Thanks for fixing it, I'll pull your changes

**Comment by zburke** [comment]
@uladislausamets : bump. This has been hanging out for a month. Could we get it merged?

**Review by NikitaSedyx — APPROVED** [review]

**Comment by uladislausamets** [comment]
merged in https://github.com/folio-org/stripes-data-transfer-components/pull/250

**Pull request closed without merging**
